name: Twilio CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies for the Twilio function
        run: npm ci
      
      - name: Install Twilio CLI and run deploy command
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
        run: |
          npm install twilio-cli -g
          twilio plugins:install @twilio-labs/plugin-serverless
          twilio serverless:deploy --service-name=example-deployed-with-github-actions --environment=dev --force